### ISSUE TITLE
Lacking persist keyword

### ISSUE THREAD

**Issue by Earnestly** [Duncaen/OpenDoas#14]
In the [doas mastery](http://www.tedunangst.com/flak/post/doas-mastery) article Tedu describes the a `persist` keyword which essentially acts as the timeout seen in `sudo`.

This doesn't appear to be available with opendoas; is this due to upstream being further ahead?

**Comment by Duncaen** [comment]
This is a very new feature, which is not even in OpenBSD releases. Only available in -current and maybe there are still changes to it until the next release.
I follow the OpenBSD releases now, because there are things in -current that get reverted and changed.
The special thing about the `persists` feature is that it uses a new kernel api that is OpenBSD only, I already wrote some code to bring the same functionality by using "cookie" files, but thats not as safe as the method OpenBSD uses as the sessions only live in the kernel and not as files on the filesystem.
If I decide to include this feature then at the time of the next OpenBSD release and only if I'm sure the code works as supposed, there are some things that can go very wrong with this, thats the reason why I wouldnt added it without a long testing and reviewing period.

**Comment by Earnestly** [comment]
Interesting, thanks for the informative response.  Good call about `persist` as well, I didn't realise it was using kernel features.

*PS: Feel free to fix my markdown screwup in the original comment, my browser is broken and I can't edit it (even with javascript globally enabled).*

**Comment by pinoaffe** [comment]
Are there any plans to add `persist` support in opendoas?

**Comment by E5ten** [comment]
After building with those flags and this being my /etc/doas.conf `permit persist :wheel` the persistence doesn't work and my password is still asked for immediately after putting it in for another command.

**Comment by TerraTech** [comment]
Any news on this being implemented into a stable release?  It would be a really nice capability to have and would be the final nail in the coffin for sudo in our devel pipeline.  :)

How does sudo implement the timeout feature?

**Comment by escondida** [comment]
Can this issue be closed now that it's supported with PAM, too?

**Comment by Duncaen** [comment]
Yes, timestamp/persist support is in master, next release should include it.

I'm going to use https://github.com/Duncaen/OpenDoas/issues/19 as tracking Issue for the next release.
