### ISSUE TITLE
Permissions on the doas binary

### ISSUE THREAD

**Issue by escondida** [Duncaen/OpenDoas#26]
In Makefile:10 , you currently set the installed doas to be only executable. Is there a reason for that? If I'm not mistaken, openbsd themselves ship it with world-readable permissions.

**Comment by Duncaen** [comment]
No real reason, I think I just went for what sudo uses by default.

**Comment by escondida** [comment]
I think that must be a packaging peculiarity; if you just ./configure; make; make install, sudo is installed 755. Would you be open to using those permissions? (The owner having write permission seems straightforward enough. If it's not owned by root, it doesn't matter, and if it is...well, if root is compromised, you have bigger problems).

**Comment by Duncaen** [comment]
Ok I guess going with `4555` like upstream is fine. `4111` might be something void specific.

**Comment by escondida** [comment]
Cool beans.

**Comment by eli-schwartz** [comment]
The owner should have write permission too. The owner can already write to the file with a single chmod call anyway.

Some packaging systems might require owner write permission in order to run packaging tasks such as stripping debug symbols. (Arch Linux is one example, see https://bugs.archlinux.org/task/43600 for discussion and rationale on why we're not sure we should do anything about it.)
