### ISSUE TITLE
command executed successfully after authentication fail

### ISSUE THREAD

**Issue by basedtho** [Duncaen/OpenDoas#28]
how is this possible?
![image](https://user-images.githubusercontent.com/44036082/73680849-15225400-46ce-11ea-91c5-10d5ab02e6e3.png)

sorry i have no slightest idea what steps i should have taken to debug this

opendoas 6.6-1
on arch linux

feel free to ask for any other info, i will help as much as i can

**Comment by treeshateorcs** [comment]
my doas.conf
```
permit persist tho
permit persist budkin
```

the second user has been deleted long time ago, just forgot about its doas entry

**Comment by Duncaen** [comment]
There is not a lot to see what happened.
My guess would be that you were already authenticated, but the single command failed to read the timestamp for some reason.

**Comment by basedtho** [comment]
you are correct

**Comment by Duncaen** [comment]
I found the bug and this should be fixed when arch linux updates the package.

**Comment by basedtho** [comment]
so this is not an upstream bug?

**Comment by Duncaen** [comment]
No of course not, upstream has added a kernel api for creating timeouts for authentications.

opendoas has to do this with hoops and hackery in userspace like sudo does to generate somewhat secure timestamp files for authentication.

This issue is not security critical, but messes up the parsing of `/proc/$pid/stat`, where opendoas gets the start time and the tty number for the timestamp file.

Failing to parse this file will result in the timestamp not being used and asking for authentication even if the timestamp would have been valid.

**Comment by escondida** [comment]
OP, since you mentioned Arch, the new release is in [community] and should be available whenever your mirror gets synched up.

**Comment by ddevault** [comment]
Can you assign a CVE to this issue?
