### ISSUE TITLE
pipeline sensitive data to doas, like sudo

### ISSUE THREAD

**Issue by linuxergr** [Duncaen/OpenDoas#33]
Hi,

How can I convert this 'echo ', Password, ' | sudo -S sh -c "command"' line, to work with doas?

Regards

**Comment by hisacro** [comment]
going through the [man](https://man.openbsd.org/doas), there's no equivalent of -S
specify your usecase (turning into XY problem)
If it's inside a script and
you want to allow only above without passwd
```
permit nopass <usr> cmd sh args -c command
```

**Comment by psposito** [comment]
Thanks for the answer, is not inside a script but is a part of code, called from one of my applications.
Therefor, this cannot be used with it and this is the point of my question.
A pipeline, would be useful, instead.

**Comment by hisacro** [comment]
> is not inside a script but is a part of code

what difference does this make? 

> this cannot be used with it 

above condition is defined in [doas.conf][https://man.openbsd.org/doas.conf]

> A pipeline, would be useful, instead

I don't see how throwing away passwd 
without encryption is useful

**Comment by psposito** [comment]
My point is that I would like to send the password to it (encrypted/unencrypted), without any such modification of doas.conf
Can this be done, or not?

**Comment by hisacro** [comment]
Nope, unless your fork your own doas :)

**Comment by psposito** [comment]
Well, I may even consider that :)

**Comment by Duncaen** [comment]
Might help if you describe your usecase, with a real example. With the limited information I have the feeling you are doing something that shouldn't be done with sudo/doas.

**Comment by psposito** [comment]
Thanks you Duncaen.

I have developed a small gui application, named Camera Control Switch https://gitea.artixlinux.org/linuxer/camera-control-webcam-switch-indicator, which is the replacement of the outdated desktop security application Camera Monitor. 

The problem is that it uses extensively the bash commands, such as lsof, for which the sudo password has to be supplied (pipelined)

In order to keep up, with better security stanards, due to sudo vulnerabilities, I am looking for an option/alternative, to use in my code.

Regards

**Comment by Duncaen** [comment]
Yea this sounds more like something that would work better with polkit or a privileged daemon, changing from sudo to doas doesn't make your program safer. You already leak the password through the environment variable or through memory, so it doesn't matter if sudo has vulnerabilities, because any program running as your user can read the password.

**Comment by psposito** [comment]
Yep, I also tried to go with polkit, but denies to open it as a gui, although it was set at the rules file/
