### ISSUE TITLE
"Authorization Failed" on Debian 10

### ISSUE THREAD

**Issue by sirfredrick** [Duncaen/OpenDoas#42]
For the latest release, v6.8 the install runs successfully and it is able to recognize the `/etc/doas.conf` file, however running any command as the non-root user results in a `doas: Authorization failed` error. This seems to be a regression from v6.6.1 as that version install and runs perfectly fine. This was done on a fresh Debian 10 install in a VM and I was also able to reproduce on my Ubuntu 20.04 based install.

/etc/doas.conf
```bash
permit user as root
```
Let me know if you need any other information.

**Comment by Duncaen** [comment]
Maybe the more generic default `/etc/pam.d/doas` file doesn't work with debian.
Other than this, needs more information like if its build with pam support or shadow or maybe no interactive authentication at all.

**Comment by NastyaGrifon** [comment]
Same error on  Ubuntu 18.04 LTS. Copying pam config didn't help

**Comment by Duncaen** [comment]
I can't really help here, providing a safe working pam configuration file for every possible distribution and version of distribution is just something that is not possible. Using the sudo configuration as example is the safest bet, otherwise you might end up with a messed up pam configuration which is insecure.

Use this software only if your distribution packages the software with the right pam configuration or if you can safely configure pam yourself.

**Comment by Duncaen** [comment]
https://github.com/Duncaen/OpenDoas#pam-configuration
