### ISSUE TITLE
yay creates new timestamp

### ISSUE THREAD

**Issue by TheCynicalTeam** [Duncaen/OpenDoas#56]
not too sure if this is ment to happen or not but when using yay and having doas symlinked to be sudo (as yay requires sudo to be installed) it seems to create a new timestamp each time and not use the current timestamp (same issue with paru)

![1612542712](https://user-images.githubusercontent.com/9284733/107061152-bbb49f80-67cf-11eb-8a20-97046183feb1.png)

**Comment by Duncaen** [comment]
Timestamp includes the parent process ID, if you run doas with a different parent process then the timestamp can't be reused.

**Comment by TheCynicalTeam** [comment]
so if i do `doas yay -Syu` is it ment to still ask for the password if i run the same thing again? right after

**Comment by Duncaen** [comment]
No, your shell is the parent process, if it stays the same then the timestamp can be used.

**Comment by TheCynicalTeam** [comment]
well thats my hole point ^^^ it asks the password every time i run it even 2 times in 5 seconds

![1612543552](https://user-images.githubusercontent.com/9284733/107062924-b35d6400-67d1-11eb-8b0b-094bd2a3c60a.png)

**Comment by Duncaen** [comment]
Your shell is not the parent process in this screenshot, if you would run `doas yay` and in your previous comment then running `doas yay` consecutively, the timestamp can be used because your shell is the parent process.

The issue is yay, either through golang and concurrency running doas from different threads or it runs doas with a new shell process as its parent or something like that.

**Comment by Duncaen** [comment]
In this screenshot the issue is just that yay is a parent process of doas and each time you execute doas from within yay the parent process is different and the timestamp will not be used.

**Comment by TheCynicalTeam** [comment]
ok so seems to be the same issue with paru :)

**Comment by Duncaen** [comment]
Its not an issue its a feature.

**Comment by Duncaen** [comment]
doas is meant to be used interactively, mainly to elevate privileges in your shell session, the persist feature allows doas to remember the authentication in limited cases, when the tty is the same, the user is the same, the parent process is the same and its run within 5 minutes.

The main reason behind this is to stop scripts or programs from executing commands with doas using a timestamp just because you happened to have used doas within 5 minutes on the same shell.

**Comment by TheCynicalTeam** [comment]
ok thats a good point :)
