### ISSUE TITLE
Researching how to configure PAM.d for Manjaro Linux to be used with Opendoas

### ISSUE THREAD

**Issue by rsramkis** [Duncaen/OpenDoas#59]
I've been reading through the arch wiki trying to determine the approach to configure pam.d  to work with Opendoas. So far I have seen comments to use the /etc/pam.d/sudo (e.g. cp /etc/pam.d/sudo /etc/pam.d/doas).

**/etc/pam.d/sudo Contents fro Manjaro Gnome:**

```
#%PAM-1.0

auth required pam_env.so
auth sufficient pam_fprintd.so
auth sufficient pam_unix.so try_first_pass likeauth nullok
auth required pam_deny.so
auth		include		system-auth
account		include		system-auth
session		include		system-auth
```
**/etc/doas.conf**

`permit testuser as root`

**Question:**

(1) How do I determine what configuration lines should be kept in this file?

(2) I am aware as I go down the road of testing I will be trying to:
      (a) Sign in as a non Root user.
      (b) Sign in as Root.
      (c) Sign in with the finger print reader.
      (d) Install applications with doas.
      (e) Run System Update (doas -- pacman -Syyu).
      (f) Repeat all tests (A to E) with sudo uninstalled.

Are there other tests I should run?

**Source:**
https://likegeeks.com/linux-pam-easy-guide/
https://wiki.archlinux.org/index.php/List_of_applications/Security

**Comment by Duncaen** [comment]
sudo and opendoas will come with just the defaults on arch linux, i.e. only the `include system-auth` lines.

I would be careful with the additions, i.e. the option `likeauth` for `pam_unix` is not even documented.
The early `auth sufficient` modules seems wrong, as far as I understand this will bypass all the other `auth` modules that are part of `system-auth`, i.e. `pam_faillock` and `pam_systemd_home`

Fingerprint authentication for root privileges seems scary to me and I personally would not do that.

> Are there other tests I should run?

Depends, I would test edge cases like dbus not working (required for pam_fprintd), fprintd not running, fingerprints available, no password available, locked account. But generally reading the documentation of pam and first writing a configuration that makes sense would make the most sense because if you know what your configuration is supposed to do, how to test it comes naturally.

**Comment by rsramkis** [comment]
Thanks for your feedback. 

I will change my assumptions around configuring the fingerprint or other sign in functionality (2 factor like a Yubikey).

https://www.theverge.com/2019/2/22/18235173/the-best-hardware-security-keys-yubico-titan-key-u2f
