### ISSUE TITLE
check of seccomp.h

### ISSUE THREAD

**Issue by frgm** [Duncaen/OpenDoas#6]
here [pledge-seccomp.c:23](https://github.com/Duncaen/OpenDoas/blob/8558e5d1f9162b66bf09820ae1281522700fe283/libopenbsd/pledge-seccomp.c#L23) includes `seccomp.h`;

here a [check](https://github.com/Duncaen/OpenDoas/blob/ba41f893e86153ac1788e971ce15b5e395247874/configure#L336) includes `linux/seccomp.h`.

Typo ?

**Comment by Duncaen** [comment]
Maybe its better to remove the seccomp support for now.
`linux/seccomp.h` is the api provided by the linux kernel, in `pledge-seccomp` I actually used `libseccomp` whis provides `seccomp.h` to simplify it a little bit while testing around.

Though i don't have the time and motivation to go through all linux syscalls and make reasonable defaults for pledge, at the moment it only blacklists syscalls that OpenBSD blacklists too.

Another thing is that seccomp can't compare paths

**Comment by frgm** [comment]
There is a port [linux-seccomp-pledge](https://lobste.rs/s/8soter/implementing_pledge_on_linux_using). Could it be used  in some future ?

**Comment by Duncaen** [comment]
Seems interesting, thanks for the link. But the current version is even more limited than mine.
Also I would like to get rid of the libseccomp dependency, if this will ever be added to doas.

iirc the seccomp filter has to be dropped again before calling `execvpe` otherwise the binary you execute has the same limitations that are only suited for `doas`.

I'm not sure if its really worth the extra code to just to limit privileges for some seconds.

**Comment by frgm** [comment]
It was deleted by commit [f577047](https://github.com/Duncaen/OpenDoas/commit/f577047ea6e6f0e4e4225200504fd694681dbed2).
